version: 1.2.{build}
image: Ubuntu1804
services:
- docker
cache:
- '~/.nuget/packages'
configuration:
- Release
before_build:
- sh: dotnet restore -v m
build:
  project: OpenRCT2.API.sln
  verbosity: minimal
test_script:
- sh: dotnet test test/ApiIntegrationTests/ApiIntegrationTests.csproj
deploy_script:
- sh: docker build -t openrct2/openrct2.api .
