version: 1.2.{build}
image: Ubuntu1804
services:
- docker
cache:
- '$HOME/.nuget/packages'
environment:
  DOCKER_USER:
    secure: G+nrMQmP95TXNwEIRCk43g==
  DOCKER_PASS:
    secure: elYPbi/YyYIbOdqadroCqQ==
configuration:
- Release
before_build:
- sh: dotnet --list-sdks
- sh: dotnet restore -v m
build:
  project: OpenRCT2.API.sln
  verbosity: minimal
test_script:
- sh: dotnet test test/ApiIntegrationTests/ApiIntegrationTests.csproj
deploy_script:
- sh: >-
    if [ $APPVEYOR_REPO_TAG = "true" ]; then

        docker build -t openrct2/openrct2.api .

        docker login -u $DOCKER_USER -p $DOCKER_PASS

        docker push openrct2/openrct2.api

        docker logout

    fi
