version: 1.1.{build}
image: Visual Studio 2017
cache:
  - '%USERPROFILE%\.nuget\packages'
configuration:
  - Release
before_build:
- cmd: dotnet restore -v m
build:
  project: OpenRCT2.API.sln
test_script:
- cmd: dotnet test test/ApiIntegrationTests/ApiIntegrationTests.csproj
